# Generated by Django 3.1.3 on 2020-11-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='ApplicationForm',
        ),
    ]
