# Generated by Django 3.1.3 on 2020-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20201111_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='phone_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
